### PR TITLE
CY3-1-Palina

### PR DESCRIPTION
**Pull request by polya26**

### CODE REVIEW

**Review by MuhammetCharyyev — APPROVED** [review]

**Comment by MuhammetCharyyev** [comment]
everything working great. I'would personaly suggest to try also function 'Keys.ENTER' after entering the password for at least one user. Just to check how enter is working with 'login ' along with 'click()'.

**Comment by polya26** [comment]
yes, you write, i will add today)

**Review by TariqEjaz — APPROVED** [review]
Done , Great coding

**Review by TariqEjaz — COMMENTED** [review]
Done

**Comment by polya26** [comment]
thanks!

**Pull request merged**
