### PR TITLE
US_3_LogOut_Muhammet

### PR DESCRIPTION
**Pull request by MuhammetCharyyev**
Please review and assign my US-3 "LogOut". I've made comments inside the Test to explain my steps. Thanks

### CODE REVIEW

**Comment by polya26** [comment]
done!

**Review by polya26 — APPROVED** [review]

**Comment by TariqEjaz** [comment]
Approved

**Review by TariqEjaz — APPROVED** [review]
Great job

**Comment by TariqEjaz** [comment]
Good job

**Pull request merged**
